/**
 * Shared data types for RoboCoder.
 *
 * This file is the "contract" between everyone's code. If the frontend, the
 * analyzer, the prompt builder, and the API all agree on these shapes, we can
 * work in parallel without breaking each other.
 *
 * Owner: Person D (Backend/Integration), but changes should be agreed by the team.
 */

/** What kind of robot we think this is. */
export type RobotType =
  | "robotic_arm"
  | "wheeled_robot"
  | "servo_mechanism"
  | "motor_mechanism"
  | "unknown";

/**
 * Which arm category this is, per docs/agent/robot-arm-agent.md §1. Only
 * meaningful when RobotType is "robotic_arm" — orthogonal to RobotType, not
 * a replacement for it.
 */
export type RobotCategory = "servo_mcu" | "industrial";

/** A single motor or servo we found on the robot. */
export interface Actuator {
  id: string;
  kind: "servo" | "dc_motor" | "stepper" | "unknown";
  model?: string; // e.g. "SG90", "MG996R", "NEMA17"
  location?: string; // e.g. "base joint", "elbow", "gripper"
}

/** Result of the perception step — what the AI understood from the upload. */
export interface RobotAnalysis {
  robotType: RobotType;
  actuators: Actuator[];
  hasEndEffector: boolean;
  endEffectorType?: "gripper" | "tool" | "none";
  description: string; // plain-language summary shown to the user
  confidence: number; // 0..1
}

/** A similar known robot / kit / SDK we matched against. */
export interface ReferenceMatch {
  name: string;
  source: string; // repo URL, SDK page, etc.
  similarity: number; // 0..1
  hasSdk: boolean;
}

/** Category A hardware — servo/MCU-driven small arm (agent spec §2A). */
export interface ServoMcuHardware {
  category: "servo_mcu";
  actuatorType: "pwm_hobby_servo" | "serial_bus_servo";
  servoBus?: "dynamixel" | "feetech" | "hiwonder" | "other";
  controlBoard: "arduino" | "esp32" | "stm32" | "pico" | "pca9685" | "other";
  hostConnection: "usb_serial" | "wifi" | "bluetooth";
  firmwareLanguage: "arduino_cpp" | "micropython" | "circuitpython";
  hostLanguage: "python" | "node" | "other";
}

/**
 * Category B hardware — brushless+reducer industrial-class arm (agent spec
 * §2B). Covers both control-stack sub-flavors (ROS2/Jetson and FRC-style
 * roboRIO/WPILib) in one shape; fields specific to a flavor are optional.
 */
export interface IndustrialHardware {
  category: "industrial";
  controlStack: "ros2" | "wpilib" | "other";
  brand?: string; // matched against the known-SDK table, if any
  sdkMatch?: SdkMatch;
  jointBus: "can" | "ethercat" | "rs485" | "proprietary" | "unknown";
  sameMachineForPanel?: boolean;

  // ros2 flavor
  compute?: "jetson_orin" | "jetson_xavier" | "jetson_nano" | "other_pc";
  jetpackVersion?: string;
  ros2Distro?: "humble" | "iron" | "jazzy" | "other";
  ros2Installed?: boolean;
  hasMoveitConfig?: boolean;
  hasRos2ControlHw?: boolean;

  // wpilib flavor
  wpilibYear?: string;
  wpilibLanguage?: "java" | "cpp" | "python";
  vendorLibs?: ("revlib" | "phoenix5" | "phoenix6" | "pathplanner")[];
}

/** Hardware details — some come from analysis, some the user fills in. */
export type HardwareInfo = ServoMcuHardware | IndustrialHardware;

/**
 * Brand/SDK lookup table entry (agent spec §2B table, mirrored here so the
 * app can match programmatically). Treat the table as a cache, not ground
 * truth — verify against upstream before hardcoding a package name into
 * generated code.
 */
export interface SdkMatch {
  brand: string;
  family?: string; // e.g. "UR3/5/10/16, e-Series"
  integrationPackage?: string; // e.g. "ur_robot_driver" or "REVLib"
  controlStack: "ros2" | "wpilib";
  hasOfficialSdk: boolean;
}

/** What the user wants the robot to do. */
export type ControlGoal =
  | "move_to_position"
  | "follow_path"
  | "gripper_open_close"
  | "set_joint_angles"
  | "autonomous_routine"
  | "manual_control"
  | "record_path"
  | "play_path";

/** A question RoboCoder asks the user to fill a gap. */
export interface Question {
  id: string;
  label: string;
  type: "text" | "select";
  options?: string[];
}

/** Everything we know, bundled together before building the prompt. */
export interface ProjectContext {
  analysis: RobotAnalysis;
  matches: ReferenceMatch[];
  hardware: HardwareInfo;
  goal: ControlGoal;
}

/**
 * Multi-turn conversation state for the gap-filling Q&A loop (agent spec
 * §2A/§2B, §3). The client round-trips this in full on every /api/session
 * call — no server-side session store for now.
 */
export interface ConversationState {
  sessionId: string;
  category?: RobotCategory;
  categoryConfirmed: boolean;
  analysis: RobotAnalysis;
  pendingQuestions: Question[];
  answers: Record<string, string>;
  hardware?: HardwareInfo;
  /**
   * Optional emphasis, not a gate: the category's deliverable bundle (agent
   * spec §4) is generated by default regardless of goal — e.g. Category B
   * always gets pose control AND record/playback together. `goal` just tells
   * the summary/generation step what to foreground, and lets the user ask
   * for a narrower scope (e.g. just gripper control) if they want less than
   * the full default bundle.
   */
  goal?: ControlGoal;
  summaryConfirmed: boolean;
}

/** Final output returned to the user. */
export interface GeneratedCode {
  files: { path: string; content: string }[];
  warnings: string[]; // e.g. "Servo model unknown — assumed SG90"
  buildPlan: string[];
  testPlan: string[];
}
